/**
 * @file Main_Web.cpp
 * @brief Web (Emscripten) entry point — boots the engine, hands the frame
 *        loop to the browser, exits clean.
 *
 * The engine's GameMain() runs `while (loop) { Update(); }`, which would
 * freeze the browser tab: the page only paints/pumps events when JS yields.
 * So this entry point does NOT call GameMain — it replicates its boot
 * sequence with the engine's public API and then registers a per-frame
 * callback via emscripten_set_main_loop (requestAnimationFrame-driven).
 * Update() itself is a clean non-blocking single frame, so no ASYNCIFY is
 * needed.
 *
 * Boot order (mirrors GameMain, Engine.cpp):
 *   ReadCommandLineArgs -> OctPreInitialize -> ReadEngineConfig ->
 *   Initialize -> OctPostInitialize -> emscripten_set_main_loop(WebFrame)
 *
 * Content arrives via the MEMFS preload bundle (<name>.data, generated by
 * the addon's PostPackage with file_packager.py): Config.ini, Content.pak /
 * the loose cooked tree, all mounted at / before main() runs. Every engine
 * read is synchronous stdio on MEMFS.
 *
 * Canvas policy: fill the browser window. OctPostInitialize sizes the canvas
 * backing store to the current window inner size (overriding Config.ini's
 * desktop resolution), and a resize callback keeps EngineState + GL viewport
 * in sync from then on (Renderer reads EngineState live every frame).
 *
 * Built only when POLYPHASE_PLATFORM_ADDON is defined.
 */

#if defined(POLYPHASE_PLATFORM_ADDON)

#include <emscripten.h>
#include <emscripten/html5.h>

#include <stdio.h>

#include "Engine.h"
#include "EngineTypes.h"
#include "EmbeddedFile.h"
#include "Log.h"

// Embedded-scripts table generated by the editor's packager into
// Generated/EmbeddedScripts.cpp at cook time. Web loads assets from the MEMFS
// bundle, but Lua scripts only ship via the embedded path, so this one blob
// is wired into the EngineConfig below.
extern uint32_t gNumEmbeddedScripts;
extern EmbeddedFile gEmbeddedScripts[];

// Graphics_WebGL2 owns the GL context; it exposes this so the resize path can
// keep the drawing-buffer size in sync with the window.
extern void WEB_OnWindowResized(uint32_t width, uint32_t height);

// C++ pure-virtual-call handler. With -fno-exceptions -fno-rtti the wasm link
// may not pull libsupc++'s copy, leaving __cxa_pure_virtual undefined against
// every abstract vtable slot. Define it here so the module links.
extern "C" void __cxa_pure_virtual()
{
    printf("FATAL: pure virtual call\n");
    for (;;) {}
}

// -------------------------------------------------------------------------
// Canvas sizing — fill the browser window.
// -------------------------------------------------------------------------

static void Web_ApplyWindowSize()
{
    double cssW = 0.0, cssH = 0.0;
    emscripten_get_element_css_size("#canvas", &cssW, &cssH);

    // The canvas is CSS-sized to the viewport by shell.html; the backing
    // store must match it in device pixels or the browser rescales (blurry).
    const double ratio = emscripten_get_device_pixel_ratio();
    uint32_t w = (uint32_t)(cssW * ratio + 0.5);
    uint32_t h = (uint32_t)(cssH * ratio + 0.5);
    if (w < 1) w = 1;
    if (h < 1) h = 1;

    emscripten_set_canvas_element_size("#canvas", (int)w, (int)h);

    GetEngineState()->mWindowWidth  = w;
    GetEngineState()->mWindowHeight = h;
    WEB_OnWindowResized(w, h);
}

static EM_BOOL Web_OnResize(int /*eventType*/, const EmscriptenUiEvent* /*e*/, void* /*userData*/)
{
    Web_ApplyWindowSize();
    return EM_TRUE;
}

static EM_BOOL Web_OnVisibilityChange(int /*eventType*/,
                                      const EmscriptenVisibilityChangeEvent* e,
                                      void* /*userData*/)
{
    GetEngineState()->mSystem.mInBackground = (e != nullptr && e->hidden);
    return EM_TRUE;
}

// -------------------------------------------------------------------------
// Oct* hooks — minimal stubs, resolved at static-init by the engine's
// OctHookAutoRegister. A game project can override by shipping its own Main
// under Source/.
// -------------------------------------------------------------------------

void OctPreInitialize(EngineConfig& config)
{
    GetEngineState()->mStandalone = true;

    config.mEmbeddedScriptCount = gNumEmbeddedScripts;
    config.mEmbeddedScripts     = gEmbeddedScripts;
}

void OctPostInitialize()
{
    // ReadEngineConfig (between the two hooks) loaded Config.ini's authored
    // desktop resolution and Initialize copied it into EngineState. The web
    // canvas fills the browser window instead — override with the live size
    // and register for resizes from here on.
    Web_ApplyWindowSize();
    emscripten_set_resize_callback(EMSCRIPTEN_EVENT_TARGET_WINDOW, nullptr,
                                   EM_TRUE, Web_OnResize);
    emscripten_set_visibilitychange_callback(nullptr, EM_TRUE, Web_OnVisibilityChange);

    LogDebug("[Web] OctPostInitialize: canvas %ux%u",
             GetEngineState()->mWindowWidth, GetEngineState()->mWindowHeight);
}

void OctPreUpdate() {}
void OctPostUpdate() {}
void OctPreShutdown() {}
void OctPostShutdown() {}

// -------------------------------------------------------------------------
// Frame loop — one callback per requestAnimationFrame.
// -------------------------------------------------------------------------

static void WebFrame()
{
    OctPreUpdate();
    const bool keepRunning = Update();
    if (!keepRunning)
    {
        OctPreShutdown();
        Shutdown();
        OctPostShutdown();
        emscripten_cancel_main_loop();
        return;
    }
    OctPostUpdate();

#if LOGGING_ENABLED
    // Once-per-second heartbeat so the browser console proves the loop is
    // alive during bring-up. Cheap enough to leave in.
    static uint32_t sFrameCount = 0;
    static double   sLastBeat = 0.0;
    ++sFrameCount;
    const double now = emscripten_get_now();
    if (now - sLastBeat >= 10000.0)
    {
        if (sLastBeat > 0.0)
        {
            LogDebug("[Web] %.1f fps (%u frames / %.1fs)",
                     sFrameCount / ((now - sLastBeat) / 1000.0),
                     sFrameCount, (now - sLastBeat) / 1000.0);
        }
        sFrameCount = 0;
        sLastBeat = now;
    }
#endif
}

// -------------------------------------------------------------------------
// Entry. The engine's own `int main` is gated out under
// POLYPHASE_PLATFORM_ADDON (Engine.cpp), so this is the sole entry point.
// -------------------------------------------------------------------------

int main(int argc, char** argv)
{
    printf("=== Polyphase Web boot ===\n");

    GetEngineState()->mArgC = argc;
    GetEngineState()->mArgV = argv;
    ReadCommandLineArgs(argc, argv);

    OctPreInitialize(*GetMutableEngineConfig());
    ReadEngineConfig();     // Config.ini out of the MEMFS bundle
    Initialize();           // mounts Content.pak, discovers the asset registry,
                            // boots GFX/AUD/INP/NET, loads the default scene
    OctPostInitialize();

    // fps=0 -> requestAnimationFrame pacing (vsync'd to the display).
    // simulate_infinite_loop=1 -> this call never returns; the runtime stays
    // alive (-sEXIT_RUNTIME=0) and WebFrame fires once per rAF.
    emscripten_set_main_loop(WebFrame, 0, 1);

    return 0; // unreached
}

#endif // POLYPHASE_PLATFORM_ADDON
